name: realview
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  build_runner: ^2.4.15
  dio: ^5.8.0+1
  easy_localization: ^3.0.7+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_launcher_icons: ^0.14.3
  get_it: ^8.0.2
  go_router: ^14.8.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.4
  logging: ^1.3.0
  requests_inspector: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/

